###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID c2s)
#  Generated on:      Fri Jul 12 15:25:21 2024
#  Design:            single_port_ram
#  Command:           create_ccopt_clock_tree_spec -file ./ClockTreeSynthesis/_ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk_pad true

# Clocks present at pin clk_pad
#   clk (period 15.000ns) in timing_config all([/run/media/user1/c2s/sriram/singlePortRAM/12_singlePortRAM_Placement/Placement/single_port_ram_place.enc.dat/mmmc/modes/all/all.sdc])
create_ccopt_clock_tree -name clk -source clk_pad -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -early -clock_tree clk 1.875
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -late -clock_tree clk 3.000
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -clock_tree clk 1.250
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk_pad 15

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:all (sdc /run/media/user1/c2s/sriram/singlePortRAM/12_singlePortRAM_Placement/Placement/single_port_ram_place.enc.dat/mmmc/modes/all/all.sdc)
create_ccopt_skew_group -name clk/all -sources clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/all true
set_ccopt_property extracted_from_clock_name -skew_group clk/all clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/all all
set_ccopt_property extracted_from_delay_corners -skew_group clk/all {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

