
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 12 2024 12:47:01 IST (Jul 12 2024 07:17:01 UTC)

// Verification Directory fv/single_port_ram 

module ram_mod_ADDRWIDTH4_DATAWIDTH8_SIZE16(clk, addr, data, cs, we,
     dataOut);
  input clk, cs, we;
  input [3:0] addr;
  input [7:0] data;
  output [7:0] dataOut;
  wire clk, cs, we;
  wire [3:0] addr;
  wire [7:0] data;
  wire [7:0] dataOut;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire n_440, n_441, n_443, n_445, n_447, n_449, n_451, n_453;
  wire n_455, n_480, n_481, n_482, n_483, n_484, n_485, n_486;
  wire n_487, n_488, n_489, n_490, n_491, n_492, n_493, n_494;
  wire n_495, n_760, n_761, n_762, n_769, n_770, n_771, n_772;
  wire n_773, n_781, n_783, n_785, n_787, n_789, n_791, n_793;
  wire n_795, n_803, n_804, n_805, n_806, n_807, n_808, n_809;
  wire n_810, n_811, n_814, n_817, n_820, n_823, n_826, n_829;
  wire n_890, n_891, n_892, n_893, n_894, n_895, n_896, n_897;
  wire n_898, n_899, n_900, n_901, n_902, n_903, n_904, n_905;
  wire n_906, n_907, n_908, n_909, n_910, n_911, n_912, n_913;
  wire n_914, n_915, n_916, n_917, n_918, n_919, n_980, n_981;
  wire n_982, n_983, n_984, n_985, n_986, n_987, n_988, n_989;
  wire n_990, n_991, n_992, n_993, n_994, n_995, n_996, n_997;
  wire n_998, n_999, n_1000, n_1001, n_1002, n_1003, n_1004, n_1005;
  wire n_1006, n_1007, n_1008, n_1009, n_1070, n_1071, n_1072, n_1073;
  wire n_1074, n_1075, n_1076, n_1077, n_1078, n_1079, n_1080, n_1081;
  wire n_1082, n_1083, n_1084, n_1085, n_1086, n_1087, n_1088, n_1089;
  wire n_1090, n_1091, n_1092, n_1093, n_1094, n_1095, n_1096, n_1097;
  wire n_1098, n_1099, n_1160, n_1161, n_1162, n_1163, n_1164, n_1165;
  wire n_1166, n_1167, n_1168, n_1169, n_1170, n_1171, n_1172, n_1173;
  wire n_1174, n_1175, n_1176, n_1177, n_1178, n_1179, n_1180, n_1181;
  wire n_1182, n_1183, n_1184, n_1185, n_1186, n_1187, n_1188, n_1189;
  wire n_1250, n_1251, n_1252, n_1253, n_1254, n_1255, n_1256, n_1257;
  wire n_1258, n_1259, n_1260, n_1261, n_1262, n_1263, n_1264, n_1265;
  wire n_1266, n_1267, n_1268, n_1269, n_1270, n_1271, n_1272, n_1273;
  wire n_1274, n_1275, n_1276, n_1277, n_1278, n_1279, n_1340, n_1341;
  wire n_1342, n_1343, n_1344, n_1345, n_1346, n_1347, n_1348, n_1349;
  wire n_1350, n_1351, n_1352, n_1353, n_1354, n_1355, n_1356, n_1357;
  wire n_1358, n_1359, n_1360, n_1361, n_1362, n_1363, n_1364, n_1365;
  wire n_1366, n_1367, n_1368, n_1369, n_1430, n_1431, n_1432, n_1433;
  wire n_1434, n_1435, n_1436, n_1437, n_1438, n_1439, n_1440, n_1441;
  wire n_1442, n_1443, n_1444, n_1445, n_1446, n_1447, n_1448, n_1449;
  wire n_1450, n_1451, n_1452, n_1453, n_1454, n_1455, n_1456, n_1457;
  wire n_1458, n_1459, n_1520, n_1521, n_1522, n_1523, n_1524, n_1525;
  wire n_1526, n_1527, n_1528, n_1529, n_1530, n_1531, n_1532, n_1533;
  wire n_1534, n_1535, n_1536, n_1537, n_1538, n_1539, n_1540, n_1541;
  wire n_1542, n_1543, n_1544, n_1545, n_1546, n_1547, n_1548, n_1549;
  wire n_1552, n_1555, n_1558, n_1561, n_1564, n_1567, n_1570, n_1573;
  wire n_1734, n_1735, n_1736, n_1737, n_1738, n_1739, n_1740, n_1741;
  wire n_1742, n_1743, n_1744, n_1745, n_1746, n_1747, n_1748, n_1749;
  CDN_flop \dataOut_reg[0] (.clk (clk), .d (n_441), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[0]));
  CDN_flop \dataOut_reg[1] (.clk (clk), .d (n_443), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[1]));
  CDN_flop \dataOut_reg[2] (.clk (clk), .d (n_445), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[2]));
  CDN_flop \dataOut_reg[3] (.clk (clk), .d (n_447), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[3]));
  CDN_flop \dataOut_reg[4] (.clk (clk), .d (n_449), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[4]));
  CDN_flop \dataOut_reg[5] (.clk (clk), .d (n_451), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[5]));
  CDN_flop \dataOut_reg[6] (.clk (clk), .d (n_453), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[6]));
  CDN_flop \dataOut_reg[7] (.clk (clk), .d (n_455), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (dataOut[7]));
  or g686 (n_440, we, wc);
  not gc (wc, cs);
  or g975 (n_807, addr[1], addr[2]);
  nand g981 (n_808, addr[1], addr[2]);
  or g1011 (n_809, addr[1], wc0);
  not gc0 (wc0, addr[2]);
  or g1012 (n_810, wc1, addr[2]);
  not gc1 (wc1, addr[1]);
  or g1519 (n_445, n_785, wc2);
  not gc2 (wc2, n_1552);
  or g1520 (n_449, n_789, wc3);
  not gc3 (wc3, n_1555);
  or g1521 (n_443, n_783, wc4);
  not gc4 (wc4, n_1558);
  or g1522 (n_455, n_795, wc5);
  not gc5 (wc5, n_1567);
  or g1523 (n_451, n_791, wc6);
  not gc6 (wc6, n_1573);
  or g1524 (n_441, n_781, wc7);
  not gc7 (wc7, n_1564);
  or g1525 (n_453, n_793, wc8);
  not gc8 (wc8, n_1570);
  or g1526 (n_447, n_787, wc9);
  not gc9 (wc9, n_1561);
  or g1527 (n_785, n_1098, n_1099);
  or g1528 (n_781, n_918, n_919);
  or g1529 (n_789, n_1278, n_1279);
  or g1530 (n_791, n_1368, n_1369);
  or g1531 (n_795, n_1548, n_1549);
  or g1532 (n_787, n_1188, n_1189);
  or g1533 (n_793, n_1458, n_1459);
  or g1534 (n_783, n_1008, n_1009);
  or g1535 (n_1279, n_1276, n_1277);
  or g1536 (n_1098, n_1094, n_1095);
  or g1537 (n_1278, n_1274, n_1275);
  or g1538 (n_1549, n_1546, n_1547);
  or g1539 (n_1548, n_1544, n_1545);
  or g1540 (n_1368, n_1364, n_1365);
  or g1541 (n_1369, n_1366, n_1367);
  or g1542 (n_1008, n_1004, n_1005);
  or g1543 (n_918, n_914, n_915);
  or g1544 (n_919, n_916, n_917);
  or g1545 (n_1099, n_1096, n_1097);
  or g1546 (n_1189, n_1186, n_1187);
  or g1547 (n_1188, n_1184, n_1185);
  or g1548 (n_1459, n_1456, n_1457);
  or g1549 (n_1458, n_1454, n_1455);
  or g1550 (n_1009, n_1006, n_1007);
  or g1551 (n_914, n_906, n_907);
  or g1552 (n_1547, n_1542, n_1543);
  or g1553 (n_1546, n_1540, n_1541);
  or g1554 (n_1545, n_1538, n_1539);
  or g1555 (n_1544, n_1536, n_1537);
  or g1556 (n_1277, n_1272, n_1273);
  or g1557 (n_1187, n_1182, n_1183);
  or g1558 (n_1186, n_1180, n_1181);
  or g1559 (n_1185, n_1178, n_1179);
  or g1560 (n_1184, n_1176, n_1177);
  or g1561 (n_1276, n_1270, n_1271);
  or g1562 (n_1006, n_1000, n_1001);
  or g1563 (n_915, n_908, n_909);
  or g1564 (n_916, n_910, n_911);
  or g1565 (n_917, n_912, n_913);
  or g1566 (n_1007, n_1002, n_1003);
  or g1567 (n_1097, n_1092, n_1093);
  or g1568 (n_1364, n_1356, n_1357);
  or g1569 (n_1365, n_1358, n_1359);
  or g1570 (n_1366, n_1360, n_1361);
  or g1571 (n_1367, n_1362, n_1363);
  or g1572 (n_1274, n_1266, n_1267);
  or g1573 (n_1004, n_996, n_997);
  or g1574 (n_1005, n_998, n_999);
  or g1575 (n_1457, n_1452, n_1453);
  or g1576 (n_1456, n_1450, n_1451);
  or g1577 (n_1455, n_1448, n_1449);
  or g1578 (n_1454, n_1446, n_1447);
  or g1579 (n_1096, n_1090, n_1091);
  or g1580 (n_1095, n_1088, n_1089);
  or g1581 (n_1094, n_1086, n_1087);
  or g1582 (n_1275, n_1268, n_1269);
  nand g1583 (n_1446, n_1430, n_1431);
  nand g1584 (n_1447, n_1432, n_1433);
  nand g1585 (n_1448, n_1434, n_1435);
  nand g1586 (n_1449, n_1436, n_1437);
  nand g1587 (n_1086, n_1070, n_1071);
  nand g1588 (n_1087, n_1072, n_1073);
  nand g1589 (n_1088, n_1074, n_1075);
  nand g1590 (n_1089, n_1076, n_1077);
  nand g1591 (n_1090, n_1078, n_1079);
  nand g1592 (n_1091, n_1080, n_1081);
  nand g1593 (n_1092, n_1082, n_1083);
  nand g1594 (n_1093, n_1084, n_1085);
  nand g1595 (n_1450, n_1438, n_1439);
  nand g1596 (n_1451, n_1440, n_1441);
  nand g1597 (n_1452, n_1442, n_1443);
  nand g1598 (n_1453, n_1444, n_1445);
  nand g1599 (n_1003, n_994, n_995);
  nand g1600 (n_1002, n_992, n_993);
  nand g1601 (n_1001, n_990, n_991);
  nand g1602 (n_1000, n_988, n_989);
  nand g1603 (n_999, n_986, n_987);
  nand g1604 (n_998, n_984, n_985);
  nand g1605 (n_1363, n_1354, n_1355);
  nand g1606 (n_1362, n_1352, n_1353);
  nand g1607 (n_1361, n_1350, n_1351);
  nand g1608 (n_1360, n_1348, n_1349);
  nand g1609 (n_1359, n_1346, n_1347);
  nand g1610 (n_1358, n_1344, n_1345);
  nand g1611 (n_1357, n_1342, n_1343);
  nand g1612 (n_1356, n_1340, n_1341);
  nand g1613 (n_997, n_982, n_983);
  nand g1614 (n_996, n_980, n_981);
  nand g1615 (n_1536, n_1520, n_1521);
  nand g1616 (n_1537, n_1522, n_1523);
  nand g1617 (n_1176, n_1160, n_1161);
  nand g1618 (n_1177, n_1162, n_1163);
  nand g1619 (n_1178, n_1164, n_1165);
  nand g1620 (n_1179, n_1166, n_1167);
  nand g1621 (n_1180, n_1168, n_1169);
  nand g1622 (n_1181, n_1170, n_1171);
  nand g1623 (n_1182, n_1172, n_1173);
  nand g1624 (n_1183, n_1174, n_1175);
  nand g1625 (n_1538, n_1524, n_1525);
  nand g1626 (n_1539, n_1526, n_1527);
  nand g1627 (n_1540, n_1528, n_1529);
  nand g1628 (n_1541, n_1530, n_1531);
  nand g1629 (n_1542, n_1532, n_1533);
  nand g1630 (n_1543, n_1534, n_1535);
  nand g1631 (n_913, n_904, n_905);
  nand g1632 (n_912, n_902, n_903);
  nand g1633 (n_911, n_900, n_901);
  nand g1634 (n_910, n_898, n_899);
  nand g1635 (n_909, n_896, n_897);
  nand g1636 (n_1273, n_1264, n_1265);
  nand g1637 (n_1272, n_1262, n_1263);
  nand g1638 (n_1271, n_1260, n_1261);
  nand g1639 (n_1270, n_1258, n_1259);
  nand g1640 (n_1269, n_1256, n_1257);
  nand g1641 (n_1268, n_1254, n_1255);
  nand g1642 (n_1267, n_1252, n_1253);
  nand g1643 (n_1266, n_1250, n_1251);
  nand g1644 (n_908, n_894, n_895);
  nand g1645 (n_907, n_892, n_893);
  nand g1646 (n_906, n_890, n_891);
  or g1647 (n_1261, n_490, wc10);
  not gc10 (wc10, \mem[10] [4]);
  or g1648 (n_1260, n_489, wc11);
  not gc11 (wc11, \mem[9] [4]);
  or g1649 (n_1259, n_488, wc12);
  not gc12 (wc12, \mem[8] [4]);
  or g1650 (n_1258, n_487, wc13);
  not gc13 (wc13, \mem[7] [4]);
  or g1651 (n_1257, n_486, wc14);
  not gc14 (wc14, \mem[6] [4]);
  or g1652 (n_1256, n_485, wc15);
  not gc15 (wc15, \mem[5] [4]);
  or g1653 (n_1255, n_484, wc16);
  not gc16 (wc16, \mem[4] [4]);
  or g1654 (n_1254, n_483, wc17);
  not gc17 (wc17, \mem[3] [4]);
  or g1655 (n_1253, n_482, wc18);
  not gc18 (wc18, \mem[2] [4]);
  or g1656 (n_1252, n_481, wc19);
  not gc19 (wc19, \mem[1] [4]);
  or g1657 (n_1251, n_480, wc20);
  not gc20 (wc20, \mem[0] [4]);
  or g1660 (n_1262, n_491, wc21);
  not gc21 (wc21, \mem[11] [4]);
  or g1661 (n_1263, n_492, wc22);
  not gc22 (wc22, \mem[12] [4]);
  or g1662 (n_1264, n_493, wc23);
  not gc23 (wc23, \mem[13] [4]);
  or g1663 (n_1265, n_494, wc24);
  not gc24 (wc24, \mem[14] [4]);
  or g1664 (n_1171, n_490, wc25);
  not gc25 (wc25, \mem[10] [3]);
  or g1665 (n_1341, n_480, wc26);
  not gc26 (wc26, \mem[0] [5]);
  or g1666 (n_1342, n_481, wc27);
  not gc27 (wc27, \mem[1] [5]);
  or g1667 (n_1343, n_482, wc28);
  not gc28 (wc28, \mem[2] [5]);
  or g1668 (n_1344, n_483, wc29);
  not gc29 (wc29, \mem[3] [5]);
  or g1669 (n_1345, n_484, wc30);
  not gc30 (wc30, \mem[4] [5]);
  or g1670 (n_1346, n_485, wc31);
  not gc31 (wc31, \mem[5] [5]);
  or g1671 (n_1347, n_486, wc32);
  not gc32 (wc32, \mem[6] [5]);
  or g1672 (n_1348, n_487, wc33);
  not gc33 (wc33, \mem[7] [5]);
  or g1673 (n_1349, n_488, wc34);
  not gc34 (wc34, \mem[8] [5]);
  or g1674 (n_1350, n_489, wc35);
  not gc35 (wc35, \mem[9] [5]);
  or g1675 (n_1175, n_494, wc36);
  not gc36 (wc36, \mem[14] [3]);
  or g1676 (n_1174, n_493, wc37);
  not gc37 (wc37, \mem[13] [3]);
  or g1677 (n_1173, n_492, wc38);
  not gc38 (wc38, \mem[12] [3]);
  or g1678 (n_1172, n_491, wc39);
  not gc39 (wc39, \mem[11] [3]);
  or g1681 (n_1170, n_489, wc40);
  not gc40 (wc40, \mem[9] [3]);
  or g1682 (n_1169, n_488, wc41);
  not gc41 (wc41, \mem[8] [3]);
  or g1683 (n_1168, n_487, wc42);
  not gc42 (wc42, \mem[7] [3]);
  or g1684 (n_1167, n_486, wc43);
  not gc43 (wc43, \mem[6] [3]);
  or g1685 (n_1166, n_485, wc44);
  not gc44 (wc44, \mem[5] [3]);
  or g1686 (n_1165, n_484, wc45);
  not gc45 (wc45, \mem[4] [3]);
  or g1687 (n_1164, n_483, wc46);
  not gc46 (wc46, \mem[3] [3]);
  or g1688 (n_1163, n_482, wc47);
  not gc47 (wc47, \mem[2] [3]);
  or g1689 (n_1162, n_481, wc48);
  not gc48 (wc48, \mem[1] [3]);
  or g1690 (n_1161, n_480, wc49);
  not gc49 (wc49, \mem[0] [3]);
  or g1693 (n_1351, n_490, wc50);
  not gc50 (wc50, \mem[10] [5]);
  or g1694 (n_1352, n_491, wc51);
  not gc51 (wc51, \mem[11] [5]);
  or g1695 (n_1353, n_492, wc52);
  not gc52 (wc52, \mem[12] [5]);
  or g1696 (n_1354, n_493, wc53);
  not gc53 (wc53, \mem[13] [5]);
  or g1697 (n_1355, n_494, wc54);
  not gc54 (wc54, \mem[14] [5]);
  or g1700 (n_1431, n_480, wc55);
  not gc55 (wc55, \mem[0] [6]);
  or g1701 (n_1432, n_481, wc56);
  not gc56 (wc56, \mem[1] [6]);
  or g1702 (n_1433, n_482, wc57);
  not gc57 (wc57, \mem[2] [6]);
  or g1703 (n_1434, n_483, wc58);
  not gc58 (wc58, \mem[3] [6]);
  or g1704 (n_1435, n_484, wc59);
  not gc59 (wc59, \mem[4] [6]);
  or g1705 (n_1436, n_485, wc60);
  not gc60 (wc60, \mem[5] [6]);
  or g1706 (n_1437, n_486, wc61);
  not gc61 (wc61, \mem[6] [6]);
  or g1707 (n_1438, n_487, wc62);
  not gc62 (wc62, \mem[7] [6]);
  or g1708 (n_1439, n_488, wc63);
  not gc63 (wc63, \mem[8] [6]);
  or g1709 (n_1085, n_494, wc64);
  not gc64 (wc64, \mem[14] [2]);
  or g1710 (n_1084, n_493, wc65);
  not gc65 (wc65, \mem[13] [2]);
  or g1711 (n_1083, n_492, wc66);
  not gc66 (wc66, \mem[12] [2]);
  or g1712 (n_1082, n_491, wc67);
  not gc67 (wc67, \mem[11] [2]);
  or g1713 (n_1081, n_490, wc68);
  not gc68 (wc68, \mem[10] [2]);
  or g1714 (n_1080, n_489, wc69);
  not gc69 (wc69, \mem[9] [2]);
  or g1715 (n_1079, n_488, wc70);
  not gc70 (wc70, \mem[8] [2]);
  or g1716 (n_1078, n_487, wc71);
  not gc71 (wc71, \mem[7] [2]);
  or g1717 (n_1077, n_486, wc72);
  not gc72 (wc72, \mem[6] [2]);
  or g1718 (n_1076, n_485, wc73);
  not gc73 (wc73, \mem[5] [2]);
  or g1719 (n_1075, n_484, wc74);
  not gc74 (wc74, \mem[4] [2]);
  or g1720 (n_1074, n_483, wc75);
  not gc75 (wc75, \mem[3] [2]);
  or g1721 (n_1073, n_482, wc76);
  not gc76 (wc76, \mem[2] [2]);
  or g1722 (n_1072, n_481, wc77);
  not gc77 (wc77, \mem[1] [2]);
  or g1723 (n_1071, n_480, wc78);
  not gc78 (wc78, \mem[0] [2]);
  or g1726 (n_1440, n_489, wc79);
  not gc79 (wc79, \mem[9] [6]);
  or g1727 (n_1441, n_490, wc80);
  not gc80 (wc80, \mem[10] [6]);
  or g1728 (n_1442, n_491, wc81);
  not gc81 (wc81, \mem[11] [6]);
  or g1729 (n_1443, n_492, wc82);
  not gc82 (wc82, \mem[12] [6]);
  or g1730 (n_1444, n_493, wc83);
  not gc83 (wc83, \mem[13] [6]);
  or g1731 (n_1445, n_494, wc84);
  not gc84 (wc84, \mem[14] [6]);
  or g1734 (n_1521, n_480, wc85);
  not gc85 (wc85, \mem[0] [7]);
  or g1735 (n_1522, n_481, wc86);
  not gc86 (wc86, \mem[1] [7]);
  or g1736 (n_1523, n_482, wc87);
  not gc87 (wc87, \mem[2] [7]);
  or g1737 (n_1524, n_483, wc88);
  not gc88 (wc88, \mem[3] [7]);
  or g1738 (n_1525, n_484, wc89);
  not gc89 (wc89, \mem[4] [7]);
  or g1739 (n_1526, n_485, wc90);
  not gc90 (wc90, \mem[5] [7]);
  or g1740 (n_1527, n_486, wc91);
  not gc91 (wc91, \mem[6] [7]);
  or g1741 (n_1528, n_487, wc92);
  not gc92 (wc92, \mem[7] [7]);
  or g1742 (n_995, n_494, wc93);
  not gc93 (wc93, \mem[14] [1]);
  or g1743 (n_994, n_493, wc94);
  not gc94 (wc94, \mem[13] [1]);
  or g1744 (n_993, n_492, wc95);
  not gc95 (wc95, \mem[12] [1]);
  or g1745 (n_992, n_491, wc96);
  not gc96 (wc96, \mem[11] [1]);
  or g1746 (n_991, n_490, wc97);
  not gc97 (wc97, \mem[10] [1]);
  or g1747 (n_990, n_489, wc98);
  not gc98 (wc98, \mem[9] [1]);
  or g1748 (n_989, n_488, wc99);
  not gc99 (wc99, \mem[8] [1]);
  or g1749 (n_988, n_487, wc100);
  not gc100 (wc100, \mem[7] [1]);
  or g1750 (n_987, n_486, wc101);
  not gc101 (wc101, \mem[6] [1]);
  or g1751 (n_986, n_485, wc102);
  not gc102 (wc102, \mem[5] [1]);
  or g1752 (n_985, n_484, wc103);
  not gc103 (wc103, \mem[4] [1]);
  or g1753 (n_984, n_483, wc104);
  not gc104 (wc104, \mem[3] [1]);
  or g1754 (n_983, n_482, wc105);
  not gc105 (wc105, \mem[2] [1]);
  or g1755 (n_982, n_481, wc106);
  not gc106 (wc106, \mem[1] [1]);
  or g1756 (n_981, n_480, wc107);
  not gc107 (wc107, \mem[0] [1]);
  or g1759 (n_1529, n_488, wc108);
  not gc108 (wc108, \mem[8] [7]);
  or g1760 (n_1530, n_489, wc109);
  not gc109 (wc109, \mem[9] [7]);
  or g1761 (n_1531, n_490, wc110);
  not gc110 (wc110, \mem[10] [7]);
  or g1762 (n_1532, n_491, wc111);
  not gc111 (wc111, \mem[11] [7]);
  or g1763 (n_1533, n_492, wc112);
  not gc112 (wc112, \mem[12] [7]);
  or g1764 (n_1534, n_493, wc113);
  not gc113 (wc113, \mem[13] [7]);
  or g1765 (n_1535, n_494, wc114);
  not gc114 (wc114, \mem[14] [7]);
  or g1766 (n_1552, n_495, wc115);
  not gc115 (wc115, \mem[15] [2]);
  or g1767 (n_1555, n_495, wc116);
  not gc116 (wc116, \mem[15] [4]);
  or g1768 (n_1558, n_495, wc117);
  not gc117 (wc117, \mem[15] [1]);
  or g1769 (n_1561, n_495, wc118);
  not gc118 (wc118, \mem[15] [3]);
  or g1770 (n_1564, n_495, wc119);
  not gc119 (wc119, \mem[15] [0]);
  or g1771 (n_1567, n_495, wc120);
  not gc120 (wc120, \mem[15] [7]);
  or g1772 (n_1570, n_495, wc121);
  not gc121 (wc121, \mem[15] [6]);
  or g1773 (n_1573, n_495, wc122);
  not gc122 (wc122, \mem[15] [5]);
  or g1774 (n_905, n_494, wc123);
  not gc123 (wc123, \mem[14] [0]);
  or g1775 (n_904, n_493, wc124);
  not gc124 (wc124, \mem[13] [0]);
  or g1776 (n_903, n_492, wc125);
  not gc125 (wc125, \mem[12] [0]);
  or g1777 (n_902, n_491, wc126);
  not gc126 (wc126, \mem[11] [0]);
  or g1778 (n_901, n_490, wc127);
  not gc127 (wc127, \mem[10] [0]);
  or g1779 (n_900, n_489, wc128);
  not gc128 (wc128, \mem[9] [0]);
  or g1780 (n_899, n_488, wc129);
  not gc129 (wc129, \mem[8] [0]);
  or g1781 (n_898, n_487, wc130);
  not gc130 (wc130, \mem[7] [0]);
  or g1782 (n_897, n_486, wc131);
  not gc131 (wc131, \mem[6] [0]);
  or g1783 (n_896, n_485, wc132);
  not gc132 (wc132, \mem[5] [0]);
  or g1784 (n_895, n_484, wc133);
  not gc133 (wc133, \mem[4] [0]);
  or g1785 (n_894, n_483, wc134);
  not gc134 (wc134, \mem[3] [0]);
  or g1786 (n_893, n_482, wc135);
  not gc135 (wc135, \mem[2] [0]);
  or g1787 (n_892, n_481, wc136);
  not gc136 (wc136, \mem[1] [0]);
  or g1788 (n_891, n_480, wc137);
  not gc137 (wc137, \mem[0] [0]);
  or g1807 (n_480, n_769, n_760);
  or g1808 (n_481, n_760, n_761);
  or g1809 (n_482, n_769, n_762);
  or g1810 (n_483, n_761, n_762);
  or g1811 (n_485, n_761, n_770);
  or g1812 (n_486, n_769, n_771);
  or g1813 (n_487, n_761, n_771);
  or g1814 (n_488, n_760, n_772);
  or g1815 (n_489, n_760, n_773);
  or g1816 (n_490, n_772, n_762);
  or g1817 (n_491, n_773, n_762);
  or g1818 (n_492, n_772, n_770);
  or g1819 (n_493, n_773, n_770);
  or g1820 (n_803, n_829, wc138);
  not gc138 (wc138, addr[0]);
  or g1821 (n_804, n_826, wc139);
  not gc139 (wc139, addr[0]);
  or g1822 (n_805, addr[0], n_826);
  or g1823 (n_494, n_772, n_771);
  or g1824 (n_806, addr[0], n_829);
  or g1825 (n_495, n_773, n_771);
  or g1826 (n_484, n_769, n_770);
  nand g1827 (n_1160, dataOut[3], n_440);
  or g1828 (n_760, addr[2], n_823);
  or g1829 (n_762, n_820, addr[2]);
  or g1830 (n_829, n_811, wc140);
  not gc140 (wc140, addr[3]);
  or g1831 (n_826, n_811, addr[3]);
  or g1832 (n_769, addr[0], n_814);
  nand g1833 (n_1340, dataOut[5], n_440);
  or g1834 (n_761, n_814, wc141);
  not gc141 (wc141, addr[0]);
  nand g1835 (n_890, dataOut[0], n_440);
  or g1836 (n_773, n_817, wc142);
  not gc142 (wc142, addr[0]);
  nand g1837 (n_980, dataOut[1], n_440);
  or g1838 (n_772, addr[0], n_817);
  nand g1839 (n_1250, dataOut[4], n_440);
  nand g1840 (n_1520, dataOut[7], n_440);
  nand g1841 (n_1070, dataOut[2], n_440);
  or g1842 (n_771, wc143, n_820);
  not gc143 (wc143, addr[2]);
  nand g1843 (n_1430, dataOut[6], n_440);
  or g1844 (n_770, n_823, wc144);
  not gc144 (wc144, addr[2]);
  nand g1845 (n_811, we, cs);
  or g1846 (n_817, we, wc145);
  not gc145 (wc145, addr[3]);
  or g1847 (n_814, we, addr[3]);
  nand g1848 (n_820, cs, addr[1]);
  or g1849 (n_823, wc146, addr[1]);
  not gc146 (wc146, cs);
  nor g1850 (n_1734, n_807, n_804);
  nor g1851 (n_1735, n_808, n_803);
  nor g1852 (n_1736, n_808, n_804);
  nor g1853 (n_1737, n_808, n_805);
  nor g1854 (n_1738, n_808, n_806);
  nor g1855 (n_1739, n_807, n_805);
  nor g1856 (n_1740, n_807, n_803);
  nor g1857 (n_1741, n_807, n_806);
  nor g1858 (n_1742, n_804, n_810);
  nor g1859 (n_1743, n_805, n_810);
  nor g1860 (n_1744, n_803, n_810);
  nor g1861 (n_1745, n_806, n_810);
  nor g1862 (n_1746, n_804, n_809);
  nor g1863 (n_1747, n_805, n_809);
  nor g1864 (n_1748, n_803, n_809);
  nor g1865 (n_1749, n_806, n_809);
  CDN_flop \mem_reg[0][0] (.clk (clk), .d (data[0]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [0]));
  CDN_flop \mem_reg[0][1] (.clk (clk), .d (data[1]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [1]));
  CDN_flop \mem_reg[0][2] (.clk (clk), .d (data[2]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [2]));
  CDN_flop \mem_reg[0][3] (.clk (clk), .d (data[3]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [3]));
  CDN_flop \mem_reg[0][4] (.clk (clk), .d (data[4]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [4]));
  CDN_flop \mem_reg[0][5] (.clk (clk), .d (data[5]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [5]));
  CDN_flop \mem_reg[0][6] (.clk (clk), .d (data[6]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [6]));
  CDN_flop \mem_reg[0][7] (.clk (clk), .d (data[7]), .sena (n_1739),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [7]));
  CDN_flop \mem_reg[1][0] (.clk (clk), .d (data[0]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [0]));
  CDN_flop \mem_reg[1][1] (.clk (clk), .d (data[1]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [1]));
  CDN_flop \mem_reg[1][2] (.clk (clk), .d (data[2]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [2]));
  CDN_flop \mem_reg[1][3] (.clk (clk), .d (data[3]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [3]));
  CDN_flop \mem_reg[1][4] (.clk (clk), .d (data[4]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [4]));
  CDN_flop \mem_reg[1][5] (.clk (clk), .d (data[5]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [5]));
  CDN_flop \mem_reg[1][6] (.clk (clk), .d (data[6]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [6]));
  CDN_flop \mem_reg[1][7] (.clk (clk), .d (data[7]), .sena (n_1734),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [7]));
  CDN_flop \mem_reg[2][0] (.clk (clk), .d (data[0]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [0]));
  CDN_flop \mem_reg[2][1] (.clk (clk), .d (data[1]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [1]));
  CDN_flop \mem_reg[2][2] (.clk (clk), .d (data[2]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [2]));
  CDN_flop \mem_reg[2][3] (.clk (clk), .d (data[3]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [3]));
  CDN_flop \mem_reg[2][4] (.clk (clk), .d (data[4]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [4]));
  CDN_flop \mem_reg[2][5] (.clk (clk), .d (data[5]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [5]));
  CDN_flop \mem_reg[2][6] (.clk (clk), .d (data[6]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [6]));
  CDN_flop \mem_reg[2][7] (.clk (clk), .d (data[7]), .sena (n_1743),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [7]));
  CDN_flop \mem_reg[3][0] (.clk (clk), .d (data[0]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [0]));
  CDN_flop \mem_reg[3][1] (.clk (clk), .d (data[1]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [1]));
  CDN_flop \mem_reg[3][2] (.clk (clk), .d (data[2]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [2]));
  CDN_flop \mem_reg[3][3] (.clk (clk), .d (data[3]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [3]));
  CDN_flop \mem_reg[3][4] (.clk (clk), .d (data[4]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [4]));
  CDN_flop \mem_reg[3][5] (.clk (clk), .d (data[5]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [5]));
  CDN_flop \mem_reg[3][6] (.clk (clk), .d (data[6]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [6]));
  CDN_flop \mem_reg[3][7] (.clk (clk), .d (data[7]), .sena (n_1742),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [7]));
  CDN_flop \mem_reg[4][0] (.clk (clk), .d (data[0]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [0]));
  CDN_flop \mem_reg[4][1] (.clk (clk), .d (data[1]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [1]));
  CDN_flop \mem_reg[4][2] (.clk (clk), .d (data[2]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [2]));
  CDN_flop \mem_reg[4][3] (.clk (clk), .d (data[3]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [3]));
  CDN_flop \mem_reg[4][4] (.clk (clk), .d (data[4]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [4]));
  CDN_flop \mem_reg[4][5] (.clk (clk), .d (data[5]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [5]));
  CDN_flop \mem_reg[4][6] (.clk (clk), .d (data[6]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [6]));
  CDN_flop \mem_reg[4][7] (.clk (clk), .d (data[7]), .sena (n_1747),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [7]));
  CDN_flop \mem_reg[5][0] (.clk (clk), .d (data[0]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [0]));
  CDN_flop \mem_reg[5][1] (.clk (clk), .d (data[1]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [1]));
  CDN_flop \mem_reg[5][2] (.clk (clk), .d (data[2]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [2]));
  CDN_flop \mem_reg[5][3] (.clk (clk), .d (data[3]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [3]));
  CDN_flop \mem_reg[5][4] (.clk (clk), .d (data[4]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [4]));
  CDN_flop \mem_reg[5][5] (.clk (clk), .d (data[5]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [5]));
  CDN_flop \mem_reg[5][6] (.clk (clk), .d (data[6]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [6]));
  CDN_flop \mem_reg[5][7] (.clk (clk), .d (data[7]), .sena (n_1746),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [7]));
  CDN_flop \mem_reg[6][0] (.clk (clk), .d (data[0]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [0]));
  CDN_flop \mem_reg[6][1] (.clk (clk), .d (data[1]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [1]));
  CDN_flop \mem_reg[6][2] (.clk (clk), .d (data[2]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [2]));
  CDN_flop \mem_reg[6][3] (.clk (clk), .d (data[3]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [3]));
  CDN_flop \mem_reg[6][4] (.clk (clk), .d (data[4]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [4]));
  CDN_flop \mem_reg[6][5] (.clk (clk), .d (data[5]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [5]));
  CDN_flop \mem_reg[6][6] (.clk (clk), .d (data[6]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [6]));
  CDN_flop \mem_reg[6][7] (.clk (clk), .d (data[7]), .sena (n_1737),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [7]));
  CDN_flop \mem_reg[7][0] (.clk (clk), .d (data[0]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [0]));
  CDN_flop \mem_reg[7][1] (.clk (clk), .d (data[1]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [1]));
  CDN_flop \mem_reg[7][2] (.clk (clk), .d (data[2]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [2]));
  CDN_flop \mem_reg[7][3] (.clk (clk), .d (data[3]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [3]));
  CDN_flop \mem_reg[7][4] (.clk (clk), .d (data[4]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [4]));
  CDN_flop \mem_reg[7][5] (.clk (clk), .d (data[5]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [5]));
  CDN_flop \mem_reg[7][6] (.clk (clk), .d (data[6]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [6]));
  CDN_flop \mem_reg[7][7] (.clk (clk), .d (data[7]), .sena (n_1736),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [7]));
  CDN_flop \mem_reg[8][0] (.clk (clk), .d (data[0]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [0]));
  CDN_flop \mem_reg[8][1] (.clk (clk), .d (data[1]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [1]));
  CDN_flop \mem_reg[8][2] (.clk (clk), .d (data[2]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [2]));
  CDN_flop \mem_reg[8][3] (.clk (clk), .d (data[3]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [3]));
  CDN_flop \mem_reg[8][4] (.clk (clk), .d (data[4]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [4]));
  CDN_flop \mem_reg[8][5] (.clk (clk), .d (data[5]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [5]));
  CDN_flop \mem_reg[8][6] (.clk (clk), .d (data[6]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [6]));
  CDN_flop \mem_reg[8][7] (.clk (clk), .d (data[7]), .sena (n_1741),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [7]));
  CDN_flop \mem_reg[9][0] (.clk (clk), .d (data[0]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [0]));
  CDN_flop \mem_reg[9][1] (.clk (clk), .d (data[1]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [1]));
  CDN_flop \mem_reg[9][2] (.clk (clk), .d (data[2]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [2]));
  CDN_flop \mem_reg[9][3] (.clk (clk), .d (data[3]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [3]));
  CDN_flop \mem_reg[9][4] (.clk (clk), .d (data[4]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [4]));
  CDN_flop \mem_reg[9][5] (.clk (clk), .d (data[5]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [5]));
  CDN_flop \mem_reg[9][6] (.clk (clk), .d (data[6]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [6]));
  CDN_flop \mem_reg[9][7] (.clk (clk), .d (data[7]), .sena (n_1740),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [7]));
  CDN_flop \mem_reg[10][0] (.clk (clk), .d (data[0]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [0]));
  CDN_flop \mem_reg[10][1] (.clk (clk), .d (data[1]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [1]));
  CDN_flop \mem_reg[10][2] (.clk (clk), .d (data[2]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [2]));
  CDN_flop \mem_reg[10][3] (.clk (clk), .d (data[3]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [3]));
  CDN_flop \mem_reg[10][4] (.clk (clk), .d (data[4]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [4]));
  CDN_flop \mem_reg[10][5] (.clk (clk), .d (data[5]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [5]));
  CDN_flop \mem_reg[10][6] (.clk (clk), .d (data[6]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [6]));
  CDN_flop \mem_reg[10][7] (.clk (clk), .d (data[7]), .sena (n_1745),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [7]));
  CDN_flop \mem_reg[11][0] (.clk (clk), .d (data[0]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [0]));
  CDN_flop \mem_reg[11][1] (.clk (clk), .d (data[1]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [1]));
  CDN_flop \mem_reg[11][2] (.clk (clk), .d (data[2]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [2]));
  CDN_flop \mem_reg[11][3] (.clk (clk), .d (data[3]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [3]));
  CDN_flop \mem_reg[11][4] (.clk (clk), .d (data[4]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [4]));
  CDN_flop \mem_reg[11][5] (.clk (clk), .d (data[5]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [5]));
  CDN_flop \mem_reg[11][6] (.clk (clk), .d (data[6]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [6]));
  CDN_flop \mem_reg[11][7] (.clk (clk), .d (data[7]), .sena (n_1744),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [7]));
  CDN_flop \mem_reg[12][0] (.clk (clk), .d (data[0]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [0]));
  CDN_flop \mem_reg[12][1] (.clk (clk), .d (data[1]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [1]));
  CDN_flop \mem_reg[12][2] (.clk (clk), .d (data[2]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [2]));
  CDN_flop \mem_reg[12][3] (.clk (clk), .d (data[3]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [3]));
  CDN_flop \mem_reg[12][4] (.clk (clk), .d (data[4]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [4]));
  CDN_flop \mem_reg[12][5] (.clk (clk), .d (data[5]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [5]));
  CDN_flop \mem_reg[12][6] (.clk (clk), .d (data[6]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [6]));
  CDN_flop \mem_reg[12][7] (.clk (clk), .d (data[7]), .sena (n_1749),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [7]));
  CDN_flop \mem_reg[13][0] (.clk (clk), .d (data[0]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [0]));
  CDN_flop \mem_reg[13][1] (.clk (clk), .d (data[1]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [1]));
  CDN_flop \mem_reg[13][2] (.clk (clk), .d (data[2]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [2]));
  CDN_flop \mem_reg[13][3] (.clk (clk), .d (data[3]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [3]));
  CDN_flop \mem_reg[13][4] (.clk (clk), .d (data[4]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [4]));
  CDN_flop \mem_reg[13][5] (.clk (clk), .d (data[5]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [5]));
  CDN_flop \mem_reg[13][6] (.clk (clk), .d (data[6]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [6]));
  CDN_flop \mem_reg[13][7] (.clk (clk), .d (data[7]), .sena (n_1748),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [7]));
  CDN_flop \mem_reg[14][0] (.clk (clk), .d (data[0]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [0]));
  CDN_flop \mem_reg[14][1] (.clk (clk), .d (data[1]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [1]));
  CDN_flop \mem_reg[14][2] (.clk (clk), .d (data[2]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [2]));
  CDN_flop \mem_reg[14][3] (.clk (clk), .d (data[3]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [3]));
  CDN_flop \mem_reg[14][4] (.clk (clk), .d (data[4]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [4]));
  CDN_flop \mem_reg[14][5] (.clk (clk), .d (data[5]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [5]));
  CDN_flop \mem_reg[14][6] (.clk (clk), .d (data[6]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [6]));
  CDN_flop \mem_reg[14][7] (.clk (clk), .d (data[7]), .sena (n_1738),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [7]));
  CDN_flop \mem_reg[15][0] (.clk (clk), .d (data[0]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [0]));
  CDN_flop \mem_reg[15][1] (.clk (clk), .d (data[1]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [1]));
  CDN_flop \mem_reg[15][2] (.clk (clk), .d (data[2]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [2]));
  CDN_flop \mem_reg[15][3] (.clk (clk), .d (data[3]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [3]));
  CDN_flop \mem_reg[15][4] (.clk (clk), .d (data[4]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [4]));
  CDN_flop \mem_reg[15][5] (.clk (clk), .d (data[5]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [5]));
  CDN_flop \mem_reg[15][6] (.clk (clk), .d (data[6]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [6]));
  CDN_flop \mem_reg[15][7] (.clk (clk), .d (data[7]), .sena (n_1735),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [7]));
endmodule

module single_port_ram(clk_pad, addr_pad, data_pad, cs_pad, we_pad);
  input clk_pad, cs_pad, we_pad;
  input [3:0] addr_pad;
  inout [7:0] data_pad;
  wire clk_pad, cs_pad, we_pad;
  wire [3:0] addr_pad;
  wire [7:0] data_pad;
  wire [7:0] dataOut;
  wire [7:0] data;
  wire [3:0] addr;
  wire clk, clock, cs, we;
  ram_mod_ADDRWIDTH4_DATAWIDTH8_SIZE16 ram_1(.clk (clk), .addr (addr),
       .data (data), .cs (cs), .we (we), .dataOut (dataOut));
  pc3b01 pc3b01_1(.OEN (we), .I (dataOut[7]), .CIN (data[7]), .PAD
       (data_pad[7]));
  pc3b01 pc3b01_2(.OEN (we), .I (dataOut[6]), .CIN (data[6]), .PAD
       (data_pad[6]));
  pc3b01 pc3b01_3(.OEN (we), .I (dataOut[5]), .CIN (data[5]), .PAD
       (data_pad[5]));
  pc3b01 pc3b01_4(.OEN (we), .I (dataOut[4]), .CIN (data[4]), .PAD
       (data_pad[4]));
  pc3b01 pc3b01_5(.OEN (we), .I (dataOut[3]), .CIN (data[3]), .PAD
       (data_pad[3]));
  pc3b01 pc3b01_6(.OEN (we), .I (dataOut[2]), .CIN (data[2]), .PAD
       (data_pad[2]));
  pc3b01 pc3b01_7(.OEN (we), .I (dataOut[1]), .CIN (data[1]), .PAD
       (data_pad[1]));
  pc3b01 pc3b01_8(.OEN (we), .I (dataOut[0]), .CIN (data[0]), .PAD
       (data_pad[0]));
  pc3c01 pc3c01_1(.CCLK (clock), .CP (clk));
  pc3d01 pc3d01_1(.PAD (clk_pad), .CIN (clock));
  pc3d01 pc3d01_2(.PAD (cs_pad), .CIN (cs));
  pc3d01 pc3d01_3(.PAD (we_pad), .CIN (we));
  pc3d01 pc3d01_4(.PAD (addr_pad[3]), .CIN (addr[3]));
  pc3d01 pc3d01_5(.PAD (addr_pad[2]), .CIN (addr[2]));
  pc3d01 pc3d01_6(.PAD (addr_pad[1]), .CIN (addr[1]));
  pc3d01 pc3d01_7(.PAD (addr_pad[0]), .CIN (addr[0]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
