
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 10 2024 14:29:42 IST (Jul 10 2024 08:59:42 UTC)

// Verification Directory fv/single_port_ram 

module ram_mod_ADDRWIDTH4_DATAWIDTH8_SIZE16(clk, addr, data, cs, we,
     oe);
  input clk, cs, we, oe;
  input [3:0] addr;
  inout [7:0] data;
  wire clk, cs, we, oe;
  wire [3:0] addr;
  wire [7:0] data;
  wire [7:0] tempMem;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire n_53, n_328, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_408, n_409, n_411, n_413, n_415, n_417;
  wire n_419, n_421, n_423, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_456, n_457, n_458, n_459, n_460;
  wire n_461, n_462, n_463, n_713, n_714, n_715, n_716, n_726;
  wire n_727, n_728, n_729, n_739, n_740, n_741, n_742, n_743;
  wire n_744, n_745, n_746, n_747, n_748, n_749, n_750, n_751;
  wire n_752, n_753, n_754, n_755, n_756, n_757, n_758, n_759;
  wire n_760, n_761, n_762, n_763, n_764, n_765, n_766, n_767;
  wire n_768, n_769, n_770, n_771, n_772, n_773, n_774, n_775;
  wire n_776, n_777, n_778, n_779, n_780, n_781, n_782, n_783;
  wire n_784, n_785, n_786, n_787, n_788, n_789, n_790, n_791;
  wire n_792, n_793, n_794, n_795, n_796, n_797, n_798, n_799;
  wire n_800, n_801, n_802, n_803, n_804, n_805, n_806, n_807;
  wire n_808, n_809, n_810, n_811, n_812, n_813, n_814, n_815;
  wire n_816, n_817, n_818, n_819, n_820, n_821, n_822, n_823;
  wire n_824, n_825, n_826, n_827, n_828, n_829, n_830, n_831;
  wire n_832, n_833, n_834, n_835, n_836, n_837, n_838, n_839;
  wire n_840, n_841, n_842, n_843, n_844, n_845, n_846, n_847;
  wire n_848, n_849, n_850, n_851, n_852, n_853, n_854, n_855;
  wire n_856, n_857, n_858, n_859, n_860, n_861, n_862, n_863;
  wire n_864, n_865, n_866, n_867, n_868, n_869, n_870, n_871;
  wire n_872, n_873, n_874, n_875, n_876, n_877, n_878, n_879;
  wire n_880, n_881, n_882, n_883, n_884, n_885, n_886, n_887;
  wire n_888, n_889, n_890, n_891, n_892, n_893, n_894, n_895;
  wire n_896, n_897, n_898, n_899;
  bufif1 g174 (data[7], tempMem[7], n_898);
  bufif1 g175 (data[6], tempMem[6], n_898);
  bufif1 g176 (data[5], tempMem[5], n_898);
  bufif1 g177 (data[4], tempMem[4], n_898);
  bufif1 g178 (data[3], tempMem[3], n_898);
  bufif1 g179 (data[2], tempMem[2], n_898);
  bufif1 g180 (data[1], tempMem[1], n_898);
  bufif1 g181 (data[0], tempMem[0], n_898);
  or g699 (n_408, we, wc);
  not gc (wc, cs);
  or g757 (n_413, n_744, wc0);
  not gc0 (wc0, n_743);
  or g758 (n_417, n_748, wc1);
  not gc1 (wc1, n_747);
  or g759 (n_409, n_740, wc2);
  not gc2 (wc2, n_739);
  or g760 (n_421, n_752, wc3);
  not gc3 (wc3, n_751);
  or g761 (n_415, n_746, wc4);
  not gc4 (wc4, n_745);
  or g762 (n_411, n_742, wc5);
  not gc5 (wc5, n_741);
  or g763 (n_419, n_750, wc6);
  not gc6 (wc6, n_749);
  or g764 (n_423, n_754, wc7);
  not gc7 (wc7, n_753);
  nand g765 (n_755, n_408, tempMem[6]);
  or g766 (n_756, n_448, wc8);
  not gc8 (wc8, \mem[0] [6]);
  or g767 (n_757, n_449, wc9);
  not gc9 (wc9, \mem[1] [6]);
  or g768 (n_758, n_450, wc10);
  not gc10 (wc10, \mem[2] [6]);
  or g769 (n_759, n_451, wc11);
  not gc11 (wc11, \mem[3] [6]);
  or g770 (n_760, n_452, wc12);
  not gc12 (wc12, \mem[4] [6]);
  or g771 (n_761, n_453, wc13);
  not gc13 (wc13, \mem[5] [6]);
  or g772 (n_762, n_454, wc14);
  not gc14 (wc14, \mem[6] [6]);
  or g773 (n_763, n_455, wc15);
  not gc15 (wc15, \mem[7] [6]);
  or g774 (n_764, n_456, wc16);
  not gc16 (wc16, \mem[8] [6]);
  or g775 (n_765, n_457, wc17);
  not gc17 (wc17, \mem[9] [6]);
  or g776 (n_766, n_458, wc18);
  not gc18 (wc18, \mem[10] [6]);
  or g777 (n_767, n_459, wc19);
  not gc19 (wc19, \mem[11] [6]);
  or g778 (n_768, n_460, wc20);
  not gc20 (wc20, \mem[12] [6]);
  or g779 (n_769, n_461, wc21);
  not gc21 (wc21, \mem[13] [6]);
  or g780 (n_770, n_462, wc22);
  not gc22 (wc22, \mem[14] [6]);
  nand g781 (n_752, n_755, n_756, n_757, n_758, n_759, n_760, n_761,
       n_762, n_763, n_764, n_765, n_766, n_767, n_768, n_769, n_770);
  or g782 (n_739, n_463, wc23);
  not gc23 (wc23, \mem[15] [0]);
  nand g783 (n_771, n_408, tempMem[1]);
  or g784 (n_772, n_448, wc24);
  not gc24 (wc24, \mem[0] [1]);
  or g785 (n_773, n_449, wc25);
  not gc25 (wc25, \mem[1] [1]);
  or g786 (n_774, n_450, wc26);
  not gc26 (wc26, \mem[2] [1]);
  or g787 (n_775, n_451, wc27);
  not gc27 (wc27, \mem[3] [1]);
  or g788 (n_776, n_452, wc28);
  not gc28 (wc28, \mem[4] [1]);
  or g789 (n_777, n_453, wc29);
  not gc29 (wc29, \mem[5] [1]);
  or g790 (n_778, n_454, wc30);
  not gc30 (wc30, \mem[6] [1]);
  or g791 (n_779, n_455, wc31);
  not gc31 (wc31, \mem[7] [1]);
  or g792 (n_780, n_456, wc32);
  not gc32 (wc32, \mem[8] [1]);
  or g793 (n_781, n_457, wc33);
  not gc33 (wc33, \mem[9] [1]);
  or g794 (n_782, n_458, wc34);
  not gc34 (wc34, \mem[10] [1]);
  or g795 (n_783, n_459, wc35);
  not gc35 (wc35, \mem[11] [1]);
  or g796 (n_784, n_460, wc36);
  not gc36 (wc36, \mem[12] [1]);
  or g797 (n_785, n_461, wc37);
  not gc37 (wc37, \mem[13] [1]);
  or g798 (n_786, n_462, wc38);
  not gc38 (wc38, \mem[14] [1]);
  nand g799 (n_742, n_771, n_772, n_773, n_774, n_775, n_776, n_777,
       n_778, n_779, n_780, n_781, n_782, n_783, n_784, n_785, n_786);
  or g800 (n_741, n_463, wc39);
  not gc39 (wc39, \mem[15] [1]);
  nand g801 (n_787, n_408, tempMem[2]);
  or g802 (n_788, n_448, wc40);
  not gc40 (wc40, \mem[0] [2]);
  or g803 (n_789, n_449, wc41);
  not gc41 (wc41, \mem[1] [2]);
  or g804 (n_790, n_450, wc42);
  not gc42 (wc42, \mem[2] [2]);
  or g805 (n_791, n_451, wc43);
  not gc43 (wc43, \mem[3] [2]);
  or g806 (n_792, n_452, wc44);
  not gc44 (wc44, \mem[4] [2]);
  or g807 (n_793, n_453, wc45);
  not gc45 (wc45, \mem[5] [2]);
  or g808 (n_794, n_454, wc46);
  not gc46 (wc46, \mem[6] [2]);
  or g809 (n_795, n_455, wc47);
  not gc47 (wc47, \mem[7] [2]);
  or g810 (n_796, n_456, wc48);
  not gc48 (wc48, \mem[8] [2]);
  or g811 (n_797, n_457, wc49);
  not gc49 (wc49, \mem[9] [2]);
  or g812 (n_798, n_458, wc50);
  not gc50 (wc50, \mem[10] [2]);
  or g813 (n_799, n_459, wc51);
  not gc51 (wc51, \mem[11] [2]);
  or g814 (n_800, n_460, wc52);
  not gc52 (wc52, \mem[12] [2]);
  or g815 (n_801, n_461, wc53);
  not gc53 (wc53, \mem[13] [2]);
  or g816 (n_802, n_462, wc54);
  not gc54 (wc54, \mem[14] [2]);
  nand g817 (n_744, n_787, n_788, n_789, n_790, n_791, n_792, n_793,
       n_794, n_795, n_796, n_797, n_798, n_799, n_800, n_801, n_802);
  or g818 (n_743, n_463, wc55);
  not gc55 (wc55, \mem[15] [2]);
  nand g819 (n_803, n_408, tempMem[3]);
  or g820 (n_804, n_448, wc56);
  not gc56 (wc56, \mem[0] [3]);
  or g821 (n_805, n_449, wc57);
  not gc57 (wc57, \mem[1] [3]);
  or g822 (n_806, n_450, wc58);
  not gc58 (wc58, \mem[2] [3]);
  or g823 (n_807, n_451, wc59);
  not gc59 (wc59, \mem[3] [3]);
  or g824 (n_808, n_452, wc60);
  not gc60 (wc60, \mem[4] [3]);
  or g825 (n_809, n_453, wc61);
  not gc61 (wc61, \mem[5] [3]);
  or g826 (n_810, n_454, wc62);
  not gc62 (wc62, \mem[6] [3]);
  or g827 (n_811, n_455, wc63);
  not gc63 (wc63, \mem[7] [3]);
  or g828 (n_812, n_456, wc64);
  not gc64 (wc64, \mem[8] [3]);
  or g829 (n_813, n_457, wc65);
  not gc65 (wc65, \mem[9] [3]);
  or g830 (n_814, n_458, wc66);
  not gc66 (wc66, \mem[10] [3]);
  or g831 (n_815, n_459, wc67);
  not gc67 (wc67, \mem[11] [3]);
  or g832 (n_816, n_460, wc68);
  not gc68 (wc68, \mem[12] [3]);
  or g833 (n_817, n_461, wc69);
  not gc69 (wc69, \mem[13] [3]);
  or g834 (n_818, n_462, wc70);
  not gc70 (wc70, \mem[14] [3]);
  nand g835 (n_746, n_803, n_804, n_805, n_806, n_807, n_808, n_809,
       n_810, n_811, n_812, n_813, n_814, n_815, n_816, n_817, n_818);
  or g836 (n_745, n_463, wc71);
  not gc71 (wc71, \mem[15] [3]);
  nand g837 (n_819, n_408, tempMem[4]);
  or g838 (n_820, n_448, wc72);
  not gc72 (wc72, \mem[0] [4]);
  or g839 (n_821, n_449, wc73);
  not gc73 (wc73, \mem[1] [4]);
  or g840 (n_822, n_450, wc74);
  not gc74 (wc74, \mem[2] [4]);
  or g841 (n_823, n_451, wc75);
  not gc75 (wc75, \mem[3] [4]);
  or g842 (n_824, n_452, wc76);
  not gc76 (wc76, \mem[4] [4]);
  or g843 (n_825, n_453, wc77);
  not gc77 (wc77, \mem[5] [4]);
  or g844 (n_826, n_454, wc78);
  not gc78 (wc78, \mem[6] [4]);
  or g845 (n_827, n_455, wc79);
  not gc79 (wc79, \mem[7] [4]);
  or g846 (n_828, n_456, wc80);
  not gc80 (wc80, \mem[8] [4]);
  or g847 (n_829, n_457, wc81);
  not gc81 (wc81, \mem[9] [4]);
  or g848 (n_830, n_458, wc82);
  not gc82 (wc82, \mem[10] [4]);
  or g849 (n_831, n_459, wc83);
  not gc83 (wc83, \mem[11] [4]);
  or g850 (n_832, n_460, wc84);
  not gc84 (wc84, \mem[12] [4]);
  or g851 (n_833, n_461, wc85);
  not gc85 (wc85, \mem[13] [4]);
  or g852 (n_834, n_462, wc86);
  not gc86 (wc86, \mem[14] [4]);
  nand g853 (n_748, n_819, n_820, n_821, n_822, n_823, n_824, n_825,
       n_826, n_827, n_828, n_829, n_830, n_831, n_832, n_833, n_834);
  or g854 (n_747, n_463, wc87);
  not gc87 (wc87, \mem[15] [4]);
  nand g855 (n_835, n_408, tempMem[5]);
  or g856 (n_836, n_448, wc88);
  not gc88 (wc88, \mem[0] [5]);
  or g857 (n_837, n_449, wc89);
  not gc89 (wc89, \mem[1] [5]);
  or g858 (n_838, n_450, wc90);
  not gc90 (wc90, \mem[2] [5]);
  or g859 (n_839, n_451, wc91);
  not gc91 (wc91, \mem[3] [5]);
  or g860 (n_840, n_452, wc92);
  not gc92 (wc92, \mem[4] [5]);
  or g861 (n_841, n_453, wc93);
  not gc93 (wc93, \mem[5] [5]);
  or g862 (n_842, n_454, wc94);
  not gc94 (wc94, \mem[6] [5]);
  or g863 (n_843, n_455, wc95);
  not gc95 (wc95, \mem[7] [5]);
  or g864 (n_844, n_456, wc96);
  not gc96 (wc96, \mem[8] [5]);
  or g865 (n_845, n_457, wc97);
  not gc97 (wc97, \mem[9] [5]);
  or g866 (n_846, n_458, wc98);
  not gc98 (wc98, \mem[10] [5]);
  or g867 (n_847, n_459, wc99);
  not gc99 (wc99, \mem[11] [5]);
  or g868 (n_848, n_460, wc100);
  not gc100 (wc100, \mem[12] [5]);
  or g869 (n_849, n_461, wc101);
  not gc101 (wc101, \mem[13] [5]);
  or g870 (n_850, n_462, wc102);
  not gc102 (wc102, \mem[14] [5]);
  nand g871 (n_750, n_835, n_836, n_837, n_838, n_839, n_840, n_841,
       n_842, n_843, n_844, n_845, n_846, n_847, n_848, n_849, n_850);
  or g872 (n_749, n_463, wc103);
  not gc103 (wc103, \mem[15] [5]);
  or g873 (n_753, n_463, wc104);
  not gc104 (wc104, \mem[15] [7]);
  nand g874 (n_851, n_408, tempMem[7]);
  or g875 (n_852, n_448, wc105);
  not gc105 (wc105, \mem[0] [7]);
  or g876 (n_853, n_449, wc106);
  not gc106 (wc106, \mem[1] [7]);
  or g877 (n_854, n_450, wc107);
  not gc107 (wc107, \mem[2] [7]);
  or g878 (n_855, n_451, wc108);
  not gc108 (wc108, \mem[3] [7]);
  or g879 (n_856, n_452, wc109);
  not gc109 (wc109, \mem[4] [7]);
  or g880 (n_857, n_453, wc110);
  not gc110 (wc110, \mem[5] [7]);
  or g881 (n_858, n_454, wc111);
  not gc111 (wc111, \mem[6] [7]);
  or g882 (n_859, n_455, wc112);
  not gc112 (wc112, \mem[7] [7]);
  or g883 (n_860, n_456, wc113);
  not gc113 (wc113, \mem[8] [7]);
  or g884 (n_861, n_457, wc114);
  not gc114 (wc114, \mem[9] [7]);
  or g885 (n_862, n_458, wc115);
  not gc115 (wc115, \mem[10] [7]);
  or g886 (n_863, n_459, wc116);
  not gc116 (wc116, \mem[11] [7]);
  or g887 (n_864, n_460, wc117);
  not gc117 (wc117, \mem[12] [7]);
  or g888 (n_865, n_461, wc118);
  not gc118 (wc118, \mem[13] [7]);
  or g889 (n_866, n_462, wc119);
  not gc119 (wc119, \mem[14] [7]);
  nand g890 (n_754, n_851, n_852, n_853, n_854, n_855, n_856, n_857,
       n_858, n_859, n_860, n_861, n_862, n_863, n_864, n_865, n_866);
  or g891 (n_751, n_463, wc120);
  not gc120 (wc120, \mem[15] [6]);
  nand g892 (n_867, n_408, tempMem[0]);
  or g893 (n_868, n_448, wc121);
  not gc121 (wc121, \mem[0] [0]);
  or g894 (n_869, n_449, wc122);
  not gc122 (wc122, \mem[1] [0]);
  or g895 (n_870, n_450, wc123);
  not gc123 (wc123, \mem[2] [0]);
  or g896 (n_871, n_451, wc124);
  not gc124 (wc124, \mem[3] [0]);
  or g897 (n_872, n_452, wc125);
  not gc125 (wc125, \mem[4] [0]);
  or g898 (n_873, n_453, wc126);
  not gc126 (wc126, \mem[5] [0]);
  or g899 (n_874, n_454, wc127);
  not gc127 (wc127, \mem[6] [0]);
  or g900 (n_875, n_455, wc128);
  not gc128 (wc128, \mem[7] [0]);
  or g901 (n_876, n_456, wc129);
  not gc129 (wc129, \mem[8] [0]);
  or g902 (n_877, n_457, wc130);
  not gc130 (wc130, \mem[9] [0]);
  or g903 (n_878, n_458, wc131);
  not gc131 (wc131, \mem[10] [0]);
  or g904 (n_879, n_459, wc132);
  not gc132 (wc132, \mem[11] [0]);
  or g905 (n_880, n_460, wc133);
  not gc133 (wc133, \mem[12] [0]);
  or g906 (n_881, n_461, wc134);
  not gc134 (wc134, \mem[13] [0]);
  or g907 (n_882, n_462, wc135);
  not gc135 (wc135, \mem[14] [0]);
  nand g908 (n_740, n_867, n_868, n_869, n_870, n_871, n_872, n_873,
       n_874, n_875, n_876, n_877, n_878, n_879, n_880, n_881, n_882);
  or g939 (n_449, n_714, n_715);
  or g944 (n_454, n_713, n_727);
  or g945 (n_452, n_713, n_726);
  or g946 (n_463, n_729, n_727);
  or g947 (n_462, n_728, n_727);
  or g948 (n_461, n_729, n_726);
  or g949 (n_460, n_728, n_726);
  or g950 (n_459, n_729, n_716);
  or g951 (n_458, n_728, n_716);
  or g952 (n_457, n_714, n_729);
  or g953 (n_451, n_715, n_716);
  or g954 (n_456, n_714, n_728);
  or g955 (n_450, n_713, n_716);
  or g956 (n_455, n_715, n_727);
  or g957 (n_448, n_713, n_714);
  or g958 (n_453, n_715, n_726);
  or g959 (n_713, addr[3], addr[0], we);
  or g960 (n_362, wc136, wc137, wc138, addr[0]);
  not gc138 (wc138, addr[1]);
  not gc137 (wc137, addr[2]);
  not gc136 (wc136, addr[3]);
  or g961 (n_361, wc139, wc140, addr[1], wc141);
  not gc141 (wc141, addr[0]);
  not gc140 (wc140, addr[2]);
  not gc139 (wc139, addr[3]);
  or g962 (n_360, wc142, wc143, addr[1], addr[0]);
  not gc143 (wc143, addr[2]);
  not gc142 (wc142, addr[3]);
  or g963 (n_359, wc144, addr[2], wc145, wc146);
  not gc146 (wc146, addr[0]);
  not gc145 (wc145, addr[1]);
  not gc144 (wc144, addr[3]);
  or g964 (n_358, wc147, addr[2], wc148, addr[0]);
  not gc148 (wc148, addr[1]);
  not gc147 (wc147, addr[3]);
  or g965 (n_357, wc149, addr[2], addr[1], wc150);
  not gc150 (wc150, addr[0]);
  not gc149 (wc149, addr[3]);
  or g966 (n_356, wc151, addr[2], addr[1], addr[0]);
  not gc151 (wc151, addr[3]);
  or g967 (n_355, addr[3], wc152, wc153, wc154);
  not gc154 (wc154, addr[0]);
  not gc153 (wc153, addr[1]);
  not gc152 (wc152, addr[2]);
  or g968 (n_354, addr[3], wc155, wc156, addr[0]);
  not gc156 (wc156, addr[1]);
  not gc155 (wc155, addr[2]);
  or g969 (n_353, addr[3], wc157, addr[1], wc158);
  not gc158 (wc158, addr[0]);
  not gc157 (wc157, addr[2]);
  or g970 (n_352, addr[3], wc159, addr[1], addr[0]);
  not gc159 (wc159, addr[2]);
  or g971 (n_351, addr[3], addr[2], wc160, wc161);
  not gc161 (wc161, addr[0]);
  not gc160 (wc160, addr[1]);
  or g972 (n_350, addr[3], addr[2], wc162, addr[0]);
  not gc162 (wc162, addr[1]);
  or g973 (n_349, addr[3], addr[2], addr[1], wc163);
  not gc163 (wc163, addr[0]);
  or g974 (n_348, addr[3], addr[2], addr[1], addr[0]);
  nand g975 (n_328, cs, we);
  nand g976 (n_53, cs, oe);
  or g977 (n_729, wc164, wc165, we);
  not gc165 (wc165, addr[0]);
  not gc164 (wc164, addr[3]);
  or g978 (n_728, wc166, addr[0], we);
  not gc166 (wc166, addr[3]);
  nand g979 (n_727, addr[1], addr[2], cs);
  or g980 (n_726, wc167, addr[1], wc168);
  not gc168 (wc168, cs);
  not gc167 (wc167, addr[2]);
  nand g981 (n_363, addr[3], addr[2], addr[1], addr[0]);
  or g982 (n_716, addr[2], wc169, wc170);
  not gc170 (wc170, cs);
  not gc169 (wc169, addr[1]);
  or g983 (n_715, addr[3], wc171, we);
  not gc171 (wc171, addr[0]);
  or g984 (n_714, addr[2], addr[1], wc172);
  not gc172 (wc172, cs);
  nor g985 (n_898, n_53, we);
  nor g986 (n_883, n_328, n_348);
  nor g987 (n_884, n_328, n_349);
  nor g988 (n_885, n_328, n_350);
  nor g989 (n_886, n_328, n_351);
  nor g990 (n_887, n_328, n_352);
  nor g991 (n_888, n_328, n_353);
  nor g992 (n_889, n_328, n_354);
  nor g993 (n_890, n_328, n_355);
  nor g994 (n_891, n_328, n_356);
  nor g995 (n_892, n_328, n_357);
  nor g996 (n_893, n_328, n_358);
  nor g997 (n_894, n_328, n_359);
  nor g998 (n_895, n_328, n_360);
  nor g999 (n_896, n_328, n_361);
  nor g1000 (n_897, n_328, n_362);
  nor g1001 (n_899, n_363, n_328);
  CDN_flop \mem_reg[0][0] (.clk (clk), .d (data[0]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [0]));
  CDN_flop \mem_reg[0][1] (.clk (clk), .d (data[1]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [1]));
  CDN_flop \mem_reg[0][2] (.clk (clk), .d (data[2]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [2]));
  CDN_flop \mem_reg[0][3] (.clk (clk), .d (data[3]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [3]));
  CDN_flop \mem_reg[0][4] (.clk (clk), .d (data[4]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [4]));
  CDN_flop \mem_reg[0][5] (.clk (clk), .d (data[5]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [5]));
  CDN_flop \mem_reg[0][6] (.clk (clk), .d (data[6]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [6]));
  CDN_flop \mem_reg[0][7] (.clk (clk), .d (data[7]), .sena (n_883),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[0] [7]));
  CDN_flop \mem_reg[1][0] (.clk (clk), .d (data[0]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [0]));
  CDN_flop \mem_reg[1][1] (.clk (clk), .d (data[1]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [1]));
  CDN_flop \mem_reg[1][2] (.clk (clk), .d (data[2]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [2]));
  CDN_flop \mem_reg[1][3] (.clk (clk), .d (data[3]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [3]));
  CDN_flop \mem_reg[1][4] (.clk (clk), .d (data[4]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [4]));
  CDN_flop \mem_reg[1][5] (.clk (clk), .d (data[5]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [5]));
  CDN_flop \mem_reg[1][6] (.clk (clk), .d (data[6]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [6]));
  CDN_flop \mem_reg[1][7] (.clk (clk), .d (data[7]), .sena (n_884),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[1] [7]));
  CDN_flop \mem_reg[2][0] (.clk (clk), .d (data[0]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [0]));
  CDN_flop \mem_reg[2][1] (.clk (clk), .d (data[1]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [1]));
  CDN_flop \mem_reg[2][2] (.clk (clk), .d (data[2]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [2]));
  CDN_flop \mem_reg[2][3] (.clk (clk), .d (data[3]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [3]));
  CDN_flop \mem_reg[2][4] (.clk (clk), .d (data[4]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [4]));
  CDN_flop \mem_reg[2][5] (.clk (clk), .d (data[5]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [5]));
  CDN_flop \mem_reg[2][6] (.clk (clk), .d (data[6]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [6]));
  CDN_flop \mem_reg[2][7] (.clk (clk), .d (data[7]), .sena (n_885),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[2] [7]));
  CDN_flop \mem_reg[3][0] (.clk (clk), .d (data[0]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [0]));
  CDN_flop \mem_reg[3][1] (.clk (clk), .d (data[1]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [1]));
  CDN_flop \mem_reg[3][2] (.clk (clk), .d (data[2]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [2]));
  CDN_flop \mem_reg[3][3] (.clk (clk), .d (data[3]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [3]));
  CDN_flop \mem_reg[3][4] (.clk (clk), .d (data[4]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [4]));
  CDN_flop \mem_reg[3][5] (.clk (clk), .d (data[5]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [5]));
  CDN_flop \mem_reg[3][6] (.clk (clk), .d (data[6]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [6]));
  CDN_flop \mem_reg[3][7] (.clk (clk), .d (data[7]), .sena (n_886),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[3] [7]));
  CDN_flop \mem_reg[4][0] (.clk (clk), .d (data[0]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [0]));
  CDN_flop \mem_reg[4][1] (.clk (clk), .d (data[1]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [1]));
  CDN_flop \mem_reg[4][2] (.clk (clk), .d (data[2]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [2]));
  CDN_flop \mem_reg[4][3] (.clk (clk), .d (data[3]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [3]));
  CDN_flop \mem_reg[4][4] (.clk (clk), .d (data[4]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [4]));
  CDN_flop \mem_reg[4][5] (.clk (clk), .d (data[5]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [5]));
  CDN_flop \mem_reg[4][6] (.clk (clk), .d (data[6]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [6]));
  CDN_flop \mem_reg[4][7] (.clk (clk), .d (data[7]), .sena (n_887),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[4] [7]));
  CDN_flop \mem_reg[5][0] (.clk (clk), .d (data[0]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [0]));
  CDN_flop \mem_reg[5][1] (.clk (clk), .d (data[1]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [1]));
  CDN_flop \mem_reg[5][2] (.clk (clk), .d (data[2]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [2]));
  CDN_flop \mem_reg[5][3] (.clk (clk), .d (data[3]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [3]));
  CDN_flop \mem_reg[5][4] (.clk (clk), .d (data[4]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [4]));
  CDN_flop \mem_reg[5][5] (.clk (clk), .d (data[5]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [5]));
  CDN_flop \mem_reg[5][6] (.clk (clk), .d (data[6]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [6]));
  CDN_flop \mem_reg[5][7] (.clk (clk), .d (data[7]), .sena (n_888),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[5] [7]));
  CDN_flop \mem_reg[6][0] (.clk (clk), .d (data[0]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [0]));
  CDN_flop \mem_reg[6][1] (.clk (clk), .d (data[1]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [1]));
  CDN_flop \mem_reg[6][2] (.clk (clk), .d (data[2]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [2]));
  CDN_flop \mem_reg[6][3] (.clk (clk), .d (data[3]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [3]));
  CDN_flop \mem_reg[6][4] (.clk (clk), .d (data[4]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [4]));
  CDN_flop \mem_reg[6][5] (.clk (clk), .d (data[5]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [5]));
  CDN_flop \mem_reg[6][6] (.clk (clk), .d (data[6]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [6]));
  CDN_flop \mem_reg[6][7] (.clk (clk), .d (data[7]), .sena (n_889),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[6] [7]));
  CDN_flop \mem_reg[7][0] (.clk (clk), .d (data[0]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [0]));
  CDN_flop \mem_reg[7][1] (.clk (clk), .d (data[1]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [1]));
  CDN_flop \mem_reg[7][2] (.clk (clk), .d (data[2]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [2]));
  CDN_flop \mem_reg[7][3] (.clk (clk), .d (data[3]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [3]));
  CDN_flop \mem_reg[7][4] (.clk (clk), .d (data[4]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [4]));
  CDN_flop \mem_reg[7][5] (.clk (clk), .d (data[5]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [5]));
  CDN_flop \mem_reg[7][6] (.clk (clk), .d (data[6]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [6]));
  CDN_flop \mem_reg[7][7] (.clk (clk), .d (data[7]), .sena (n_890),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[7] [7]));
  CDN_flop \mem_reg[8][0] (.clk (clk), .d (data[0]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [0]));
  CDN_flop \mem_reg[8][1] (.clk (clk), .d (data[1]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [1]));
  CDN_flop \mem_reg[8][2] (.clk (clk), .d (data[2]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [2]));
  CDN_flop \mem_reg[8][3] (.clk (clk), .d (data[3]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [3]));
  CDN_flop \mem_reg[8][4] (.clk (clk), .d (data[4]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [4]));
  CDN_flop \mem_reg[8][5] (.clk (clk), .d (data[5]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [5]));
  CDN_flop \mem_reg[8][6] (.clk (clk), .d (data[6]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [6]));
  CDN_flop \mem_reg[8][7] (.clk (clk), .d (data[7]), .sena (n_891),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[8] [7]));
  CDN_flop \mem_reg[9][0] (.clk (clk), .d (data[0]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [0]));
  CDN_flop \mem_reg[9][1] (.clk (clk), .d (data[1]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [1]));
  CDN_flop \mem_reg[9][2] (.clk (clk), .d (data[2]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [2]));
  CDN_flop \mem_reg[9][3] (.clk (clk), .d (data[3]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [3]));
  CDN_flop \mem_reg[9][4] (.clk (clk), .d (data[4]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [4]));
  CDN_flop \mem_reg[9][5] (.clk (clk), .d (data[5]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [5]));
  CDN_flop \mem_reg[9][6] (.clk (clk), .d (data[6]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [6]));
  CDN_flop \mem_reg[9][7] (.clk (clk), .d (data[7]), .sena (n_892),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[9] [7]));
  CDN_flop \mem_reg[10][0] (.clk (clk), .d (data[0]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [0]));
  CDN_flop \mem_reg[10][1] (.clk (clk), .d (data[1]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [1]));
  CDN_flop \mem_reg[10][2] (.clk (clk), .d (data[2]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [2]));
  CDN_flop \mem_reg[10][3] (.clk (clk), .d (data[3]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [3]));
  CDN_flop \mem_reg[10][4] (.clk (clk), .d (data[4]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [4]));
  CDN_flop \mem_reg[10][5] (.clk (clk), .d (data[5]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [5]));
  CDN_flop \mem_reg[10][6] (.clk (clk), .d (data[6]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [6]));
  CDN_flop \mem_reg[10][7] (.clk (clk), .d (data[7]), .sena (n_893),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[10] [7]));
  CDN_flop \mem_reg[11][0] (.clk (clk), .d (data[0]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [0]));
  CDN_flop \mem_reg[11][1] (.clk (clk), .d (data[1]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [1]));
  CDN_flop \mem_reg[11][2] (.clk (clk), .d (data[2]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [2]));
  CDN_flop \mem_reg[11][3] (.clk (clk), .d (data[3]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [3]));
  CDN_flop \mem_reg[11][4] (.clk (clk), .d (data[4]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [4]));
  CDN_flop \mem_reg[11][5] (.clk (clk), .d (data[5]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [5]));
  CDN_flop \mem_reg[11][6] (.clk (clk), .d (data[6]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [6]));
  CDN_flop \mem_reg[11][7] (.clk (clk), .d (data[7]), .sena (n_894),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[11] [7]));
  CDN_flop \mem_reg[12][0] (.clk (clk), .d (data[0]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [0]));
  CDN_flop \mem_reg[12][1] (.clk (clk), .d (data[1]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [1]));
  CDN_flop \mem_reg[12][2] (.clk (clk), .d (data[2]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [2]));
  CDN_flop \mem_reg[12][3] (.clk (clk), .d (data[3]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [3]));
  CDN_flop \mem_reg[12][4] (.clk (clk), .d (data[4]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [4]));
  CDN_flop \mem_reg[12][5] (.clk (clk), .d (data[5]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [5]));
  CDN_flop \mem_reg[12][6] (.clk (clk), .d (data[6]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [6]));
  CDN_flop \mem_reg[12][7] (.clk (clk), .d (data[7]), .sena (n_895),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[12] [7]));
  CDN_flop \mem_reg[13][0] (.clk (clk), .d (data[0]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [0]));
  CDN_flop \mem_reg[13][1] (.clk (clk), .d (data[1]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [1]));
  CDN_flop \mem_reg[13][2] (.clk (clk), .d (data[2]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [2]));
  CDN_flop \mem_reg[13][3] (.clk (clk), .d (data[3]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [3]));
  CDN_flop \mem_reg[13][4] (.clk (clk), .d (data[4]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [4]));
  CDN_flop \mem_reg[13][5] (.clk (clk), .d (data[5]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [5]));
  CDN_flop \mem_reg[13][6] (.clk (clk), .d (data[6]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [6]));
  CDN_flop \mem_reg[13][7] (.clk (clk), .d (data[7]), .sena (n_896),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[13] [7]));
  CDN_flop \mem_reg[14][0] (.clk (clk), .d (data[0]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [0]));
  CDN_flop \mem_reg[14][1] (.clk (clk), .d (data[1]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [1]));
  CDN_flop \mem_reg[14][2] (.clk (clk), .d (data[2]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [2]));
  CDN_flop \mem_reg[14][3] (.clk (clk), .d (data[3]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [3]));
  CDN_flop \mem_reg[14][4] (.clk (clk), .d (data[4]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [4]));
  CDN_flop \mem_reg[14][5] (.clk (clk), .d (data[5]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [5]));
  CDN_flop \mem_reg[14][6] (.clk (clk), .d (data[6]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [6]));
  CDN_flop \mem_reg[14][7] (.clk (clk), .d (data[7]), .sena (n_897),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[14] [7]));
  CDN_flop \mem_reg[15][0] (.clk (clk), .d (data[0]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [0]));
  CDN_flop \mem_reg[15][1] (.clk (clk), .d (data[1]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [1]));
  CDN_flop \mem_reg[15][2] (.clk (clk), .d (data[2]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [2]));
  CDN_flop \mem_reg[15][3] (.clk (clk), .d (data[3]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [3]));
  CDN_flop \mem_reg[15][4] (.clk (clk), .d (data[4]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [4]));
  CDN_flop \mem_reg[15][5] (.clk (clk), .d (data[5]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [5]));
  CDN_flop \mem_reg[15][6] (.clk (clk), .d (data[6]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [6]));
  CDN_flop \mem_reg[15][7] (.clk (clk), .d (data[7]), .sena (n_899),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\mem[15] [7]));
  CDN_flop \tempMem_reg[0] (.clk (clk), .d (n_409), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[0]));
  CDN_flop \tempMem_reg[1] (.clk (clk), .d (n_411), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[1]));
  CDN_flop \tempMem_reg[2] (.clk (clk), .d (n_413), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[2]));
  CDN_flop \tempMem_reg[3] (.clk (clk), .d (n_415), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[3]));
  CDN_flop \tempMem_reg[4] (.clk (clk), .d (n_417), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[4]));
  CDN_flop \tempMem_reg[5] (.clk (clk), .d (n_419), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[5]));
  CDN_flop \tempMem_reg[6] (.clk (clk), .d (n_421), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[6]));
  CDN_flop \tempMem_reg[7] (.clk (clk), .d (n_423), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tempMem[7]));
endmodule

module single_port_ram(clk_pad, addr_pad, data_pad, cs_pad, we_pad,
     oe_pad);
  input clk_pad, cs_pad, we_pad, oe_pad;
  input [3:0] addr_pad;
  inout [7:0] data_pad;
  wire clk_pad, cs_pad, we_pad, oe_pad;
  wire [3:0] addr_pad;
  wire [7:0] data_pad;
  wire [7:0] data;
  wire [3:0] addr;
  wire clk, clock, cs, oe, we;
  ram_mod_ADDRWIDTH4_DATAWIDTH8_SIZE16 ram_1(.clk (clk), .addr (addr),
       .data (data), .cs (cs), .we (we), .oe (oe));
  pc3b01 pc3b01_1(.OEN (oe), .I (data[7]), .CIN (data[7]), .PAD
       (data_pad[7]));
  pc3b01 pc3b01_2(.OEN (oe), .I (data[6]), .CIN (data[6]), .PAD
       (data_pad[6]));
  pc3b01 pc3b01_3(.OEN (oe), .I (data[5]), .CIN (data[5]), .PAD
       (data_pad[5]));
  pc3b01 pc3b01_4(.OEN (oe), .I (data[4]), .CIN (data[4]), .PAD
       (data_pad[4]));
  pc3b01 pc3b01_5(.OEN (oe), .I (data[3]), .CIN (data[3]), .PAD
       (data_pad[3]));
  pc3b01 pc3b01_6(.OEN (oe), .I (data[2]), .CIN (data[2]), .PAD
       (data_pad[2]));
  pc3b01 pc3b01_7(.OEN (oe), .I (data[1]), .CIN (data[1]), .PAD
       (data_pad[1]));
  pc3b01 pc3b01_8(.OEN (oe), .I (data[0]), .CIN (data[0]), .PAD
       (data_pad[0]));
  pc3c01 pc3c01_1(.CCLK (clock), .CP (clk));
  pc3d01 pc3d01_1(.PAD (clk_pad), .CIN (clock));
  pc3d01 pc3d01_2(.PAD (cs_pad), .CIN (cs));
  pc3d01 pc3d01_3(.PAD (we_pad), .CIN (we));
  pc3d01 pc3d01_4(.PAD (oe_pad), .CIN (oe));
  pc3d01 pc3d01_5(.PAD (addr_pad[3]), .CIN (addr[3]));
  pc3d01 pc3d01_6(.PAD (addr_pad[2]), .CIN (addr[2]));
  pc3d01 pc3d01_7(.PAD (addr_pad[1]), .CIN (addr[1]));
  pc3d01 pc3d01_8(.PAD (addr_pad[0]), .CIN (addr[0]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
